// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYxY_OCJ1yBiNq4EmHn5GzjSxTZ42Tk8',
    appId: '1:830792321643:android:b1690ab5df294303547f2e',
    messagingSenderId: '830792321643',
    projectId: 'multi-ecommerce-jellysoft',
    databaseURL: 'https://multi-ecommerce-jellysoft-default-rtdb.firebaseio.com',
    storageBucket: 'multi-ecommerce-jellysoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANSyqp1crl4ruuba-btugIu12ZAe78dk',
    appId: '1:830792321643:ios:421957032acc894a547f2e',
    messagingSenderId: '830792321643',
    projectId: 'multi-ecommerce-jellysoft',
    databaseURL: 'https://multi-ecommerce-jellysoft-default-rtdb.firebaseio.com',
    storageBucket: 'multi-ecommerce-jellysoft.appspot.com',
    iosClientId: '830792321643-e52jdjffe2aipb68uqbf6ls02sbd4946.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.sixValley',
  );
}
